title: Mood Music Study
description: Researching the relationship between music and mood.
show_downloads: false
theme: minima
description: Information about the Mood Music Study.
author:
  name: Nina Di Cara
  email: nina.dicara@bristol.ac.uk
