title: Mood Music Study
description: Researching the relationship between music and mood.
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
description: Instructions for participating in the Mood Music Study.
